/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p3_escritoriosmm;

import java.awt.event.ActionEvent;

/**
 *
 * @author Alejandro
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        BotonArchivo = new javax.swing.JMenu();
        BotonNuevo = new javax.swing.JMenuItem();
        BotonAbrir = new javax.swing.JMenuItem();
        BototnGuardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        BotonImprimir = new javax.swing.JMenu();
        BotonImpresora = new javax.swing.JMenuItem();
        BotonFichero = new javax.swing.JMenuItem();
        BotonEditarr = new javax.swing.JMenu();
        BotonCopiar = new javax.swing.JMenuItem();
        BotonCortar = new javax.swing.JMenuItem();
        BotonPegar = new javax.swing.JMenuItem();
        BotonVer = new javax.swing.JMenu();
        BotonBarradeEstado = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escritorio SMM");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        BotonArchivo.setText("Archivo");
        BotonArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonArchivoMouseClicked(evt);
            }
        });
        BotonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArchivoActionPerformed(evt);
            }
        });

        BotonNuevo.setText("Nuevo");
        BotonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonNuevoMouseClicked(evt);
            }
        });
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        BotonArchivo.add(BotonNuevo);

        BotonAbrir.setText("Abrir");
        BotonArchivo.add(BotonAbrir);

        BototnGuardar.setText("Guardar");
        BotonArchivo.add(BototnGuardar);
        BotonArchivo.add(jSeparator1);

        BotonImprimir.setText("Imprimir");

        BotonImpresora.setText("Impresora");
        BotonImprimir.add(BotonImpresora);

        BotonFichero.setText("Fichero");
        BotonImprimir.add(BotonFichero);

        BotonArchivo.add(BotonImprimir);

        jMenuBar1.add(BotonArchivo);

        BotonEditarr.setText("Editar");

        BotonCopiar.setText("Copiar");
        BotonCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCopiarActionPerformed(evt);
            }
        });
        BotonEditarr.add(BotonCopiar);

        BotonCortar.setText("Cortar");
        BotonEditarr.add(BotonCortar);

        BotonPegar.setText("Pegar");
        BotonEditarr.add(BotonPegar);

        jMenuBar1.add(BotonEditarr);

        BotonVer.setText("Ver");

        BotonBarradeEstado.setSelected(true);
        BotonBarradeEstado.setText("Barra de Estado");
        BotonVer.add(BotonBarradeEstado);

        jMenuBar1.add(BotonVer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonArchivoMouseClicked

    }//GEN-LAST:event_BotonArchivoMouseClicked

    private void BotonCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCopiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCopiarActionPerformed

    private void BotonNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNuevoMouseClicked
    
    }//GEN-LAST:event_BotonNuevoMouseClicked

    private void BotonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArchivoActionPerformed

    }//GEN-LAST:event_BotonArchivoActionPerformed

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        Escritorio.add(vi);
        vi.setVisible(true);
    }//GEN-LAST:event_BotonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BotonAbrir;
    private javax.swing.JMenu BotonArchivo;
    private javax.swing.JCheckBoxMenuItem BotonBarradeEstado;
    private javax.swing.JMenuItem BotonCopiar;
    private javax.swing.JMenuItem BotonCortar;
    private javax.swing.JMenu BotonEditarr;
    private javax.swing.JMenuItem BotonFichero;
    private javax.swing.JMenuItem BotonImpresora;
    private javax.swing.JMenu BotonImprimir;
    private javax.swing.JMenuItem BotonNuevo;
    private javax.swing.JMenuItem BotonPegar;
    private javax.swing.JMenu BotonVer;
    private javax.swing.JMenuItem BototnGuardar;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
